name: Run template

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create from template
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'organization-template'
    env:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    steps:
      - name: Checkout repository
        if: env.WORKFLOW_TOKEN == null
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout repository
        if: env.WORKFLOW_TOKEN != null
        uses: actions/checkout@v2
        with:
          lfs: true
          token: ${{ env.WORKFLOW_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Run main.py
        run: python -m pip install requests && python main.py $GITHUB_REPOSITORY
      - name: Run main.py
        if: env.WORKFLOW_TOKEN == null
        run: mv .github github
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Template files created"
          git branch -M main template
          git checkout --orphan main
          git rm -rf .
          git commit --allow-empty --allow-empty-message -m "Initial commit"
          git merge --squash --allow-unrelated-histories template
          git lfs track *.png
          git lfs track *.jpg
          git lfs track *.jpeg
          git lfs track *.ico
          git lfs track *.icns
          git add .
          git commit --amend -m "Initial commit"
          git branch -D template
          git rebase --root
          git push --force -u origin main
